Repository motlabs/motlabs.github.io, pull requests merged in 2018-06, with the labels that each got.

#5 fix mistyping commands
  README.md
Labels: invalid

#11 Fix git clone url
  README.md
Labels: wontfix

#13 New posting
  _config.yml
  _posts/2018-06-09-TFContribution.md
Labels: new posting

#14 google-analytics 추가
  _config.yml
Labels: enhancement

#20 슬라이드 width값 수정
  _posts/2018-06-11-tfpattern-week2.md
Labels: bug

#40 Feature/fb tf study week4,5
  _posts/2018-06-30-tfpattern-week4.md
  _posts/2018-06-30-tfpattern-week5.md
  assets/images/tfpattern-week4/tensorflow_logo.png
  assets/images/tfpattern-week5/tensorflow_logo.png
Labels: new posting
